name = "Create Plus RedskySMP"
author = "DorrelRedmond"
version = "2.0-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60597fcab5edc88a59754640d7b7318fbe4d104e34ebd25c302bfbbb7af9beb2"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
