name = "Create Plus RedskySMP"
author = "DorrelRedmond"
version = "2.0-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65e996f45b92a30d8d8414d39dc9961782755b473cbd5bb92f56c47f5f76633e"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
