name = "RedskySMP"
author = "DorrelRedmond"
version = "1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e09a30813dc9b50e8462a5edb28bd6e0e03c462b22e403fe12224e3b4581a20f"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
